### PR TITLE
random 1.1

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by spl** [comment]
Just what I was looking for! :+1:

There are now 3 outstanding pull requests to bump the upper bounds of `random` (#7 from Oct 2014 and #8 from Dec 2014), and they all have different diffs.

@batterseapower never responded to my pull request from Feb 2014 (batterseapower/edit-distance#2). Despite having public activity since that time, I'm afraid he's no longer maintaining a number of packages, including this one.

**Comment by snoyberg** [comment]
Pinging @manny-fp. My concern about this is its inclusion in Stackage. I may need to remove parallel-io if this issue isn't resolved soon. Another possibility would be asking the Hackage janitors to bump the bound (@hvr would I speak to you about that?), or forking the package.

**Comment by hvr** [comment]
@snoyberg I believe @cartazio may have more experience with handling cases of unresponsive upstreams

**Comment by cartazio** [comment]
has anyone emailed Max? He's super responsive to email

**Comment by cartazio** [comment]
and by super responsive i meant actually does stuff within a handful of days after email. If anyone does such an email, please CC me (or the libraries list if you want it to be more public for some reason) so theres somepaper trail of emails

**Comment by cartazio** [comment]
@snoyberg  email max and CC me, he probably will respond pretty quickly to email, and ccing me makes sure that if he doesnt respond i can justify taking actiong

**Comment by snoyberg** [comment]
I've emailed @batterseapower with @cartazio CCed. I've set a reminder for myself on this subject for next Monday, so if there's no progress by then, I'll bring it up again.

**Comment by snoyberg** [comment]
@cartazio No response yet. Should we move ahead with plan B?

**Comment by snoyberg** [comment]
@cartazio Ping

**Comment by cartazio** [comment]
i'll get to replying to things this weekend, busy week

**Comment by cartazio** [comment]
Ok, 
SO i can take action today or tomorrow evening (finally)
@snoyberg  I assume you've tested this patch?
If so, i'm down with having the immediate near term thing being suitably bumping the version bounds on hackage, which either I or HVR can do for now.

**Comment by cartazio** [comment]
that still leaves the question of maintainership and such, but near term triage first!

**Comment by cartazio** [comment]
@snoyberg @hvr i did a revision on 0.3.3 for now. please test :)

**Comment by snoyberg** [comment]
Seems to be working to me @cartazio, thanks! I just pinged you on a related issue (arithmoi).

Leaving this PR open as the repo itself isn't yet fixed.

**Comment by batterseapower** [comment]
Thanks all and sorry for the trouble.

**Comment by qrilka** [comment]
@batterseapower any plans for a new release?

**Comment by qrilka** [comment]
actually it looks like deps were upped on hackage so probably it's not required

**Pull request merged**
